// <auto-generated />
using System;
using EcdlBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcdlBooking.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251013193631_Seeding_Admin")]
    partial class Seeding_Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcdlBooking.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Born")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("familyContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("familyContactPerson_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("familyContactPerson_phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdSchool");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f5de216-b03f-43d2-b0a1-4f9d6bb5c126",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e569cc1-d487-4a7d-a1ac-39274065eb42",
                            Email = "gianmarco.lunardi@iis-bressanone.edu.com",
                            EmailConfirmed = true,
                            IdSchool = new Guid("a361e1b4-5427-463c-abc8-f2f176821181"),
                            LockoutEnabled = false,
                            NormalizedEmail = "GIANMARCO.LUNARDI@IIS-BRESSANONE.EDU.COM",
                            NormalizedUserName = "GIANMARCO_LUNARDI",
                            PasswordHash = "AQAAAAEAACcQAAAAEJk1vQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQwQkQw==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "72a47951-3867-403d-9ee8-eaad38b9d269",
                            TwoFactorEnabled = false,
                            UserName = "Gianmarco_Lunardi"
                        });
                });

            modelBuilder.Entity("EcdlBooking.Models.Exam", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("EsaminatoreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("IdEsaminatore")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSchool")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoSessione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("EsaminatoreId");

                    b.HasIndex("IdSchool");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("EcdlBooking.Models.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moduli");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94f1d7b2-232b-4542-a395-98f97c371326"),
                            Nome = "Computer Essentials"
                        },
                        new
                        {
                            Id = new Guid("c2642c79-1742-47a8-a7aa-18eb853b1906"),
                            Nome = "Online Essentials"
                        },
                        new
                        {
                            Id = new Guid("2f67549b-efd9-4fb7-a84e-4837e519b925"),
                            Nome = "Word Processing"
                        },
                        new
                        {
                            Id = new Guid("ff8dc93f-98b5-4f0e-a19b-5e7b85df3bdd"),
                            Nome = "Spreadsheet"
                        },
                        new
                        {
                            Id = new Guid("a6d7b193-df8f-4691-9ea7-260dbd6c985c"),
                            Nome = "Presentation"
                        },
                        new
                        {
                            Id = new Guid("c009dd27-ce86-4f24-80a1-f453e5a7612d"),
                            Nome = "Online Collaboration"
                        },
                        new
                        {
                            Id = new Guid("663f6c0f-6843-4ddf-af2b-bd96503d1dbb"),
                            Nome = "Database"
                        });
                });

            modelBuilder.Entity("EcdlBooking.Models.SchedulerEcdl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdEsame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoEsame")
                        .HasColumnType("int");

                    b.Property<float>("Voto")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("SchedulerExams");
                });

            modelBuilder.Entity("EcdlBooking.Models.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a361e1b4-5427-463c-abc8-f2f176821181"),
                            Address = "Via Pra' delle Suore 1/A",
                            City = "Bressanone",
                            Name = "ITE LICEO Falcone Borsellino"
                        },
                        new
                        {
                            Id = new Guid("a37260f3-ec66-4787-a60d-2baa24aefa5a"),
                            Address = "Via Pra' delle Suore 1/A",
                            City = "Bressanone",
                            Name = "FP Enrico Mattei"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "26723492-169e-4ef7-941c-fa87c060d0d8",
                            Name = "Studente",
                            NormalizedName = "STUDENTE"
                        },
                        new
                        {
                            Id = "7a4edc4a-6ad0-466b-929c-73a8f769fa5e",
                            Name = "Insegnante",
                            NormalizedName = "INSEGNANTE"
                        },
                        new
                        {
                            Id = "2a1447a0-8c6a-46e9-b187-25a28e8da50e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcdlBooking.Models.ApplicationUser", b =>
                {
                    b.HasOne("EcdlBooking.Models.School", "School")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("IdSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EcdlBooking.Models.Exam", b =>
                {
                    b.HasOne("EcdlBooking.Models.ApplicationUser", "Esaminatore")
                        .WithMany("Esami")
                        .HasForeignKey("EsaminatoreId");

                    b.HasOne("EcdlBooking.Models.School", "School")
                        .WithMany("Exam")
                        .HasForeignKey("IdSchool")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Esaminatore");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcdlBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcdlBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcdlBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcdlBooking.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcdlBooking.Models.ApplicationUser", b =>
                {
                    b.Navigation("Esami");
                });

            modelBuilder.Entity("EcdlBooking.Models.School", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("Exam");
                });
#pragma warning restore 612, 618
        }
    }
}
